on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 1 * * *'

name: R-CMD-check


jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'windows-latest', 'macOS-latest']
        tf: ['2.5']

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (TF ${{ matrix.tf }})
    continue-on-error: ${{ matrix.tf == 'nightly' }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: 'true'
      TF_VERSION: ${{ matrix.tf }}
      PIP_NO_WARN_SCRIPT_LOCATION: 'false'
      RETICULATE_AUTOCONFIGURE: 'FALSE'
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      OS_LABEL: ${{ matrix.os }}


    steps:
      - name: Configure RSPM
        if: runner.os == 'Linux' # startsWith(matrix.os, 'ubuntu')
        run: |
          echo "RSPM=https://packagemanager.rstudio.com/all/__linux__/$(lsb_release -cs)/latest" >> $GITHUB_ENV

      - name: Configure reticulate miniconda path
        run: |
          echo "RETICULATE_MINICONDA_PATH=${RUNNER_TEMP}/r-miniconda" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          Ncpus: '2L'
          install-r: false

      - uses: r-lib/actions/setup-pandoc@master

      - name: Get R version
        id: r-version
        run: |
          writeLines(sprintf(
            "::set-output name=major-minor::R-%s.%s", R.version$major, R.version$minor))
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        id: r-package-cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.os }}--${{ steps.r-version.outputs.major-minor }}
          restore-keys: ${{ runner.os }}--${{ steps.r-version.outputs.major-minor }}

      - name: Install remotes
        if: steps.r-package-cache.outputs.cache-hit != 'true'
        run: install.packages("remotes")
        shell: Rscript {0}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements(Sys.getenv("OS_LABEL")))')
          # sudo apt-get install -y python3-venv

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          # remotes::install_github('rstudio/reticulate')
          # remotes::install_github('rstudio/tensorflow')
          remotes::update_packages()
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_local()

      - name: Restore r-miniconda
        uses: actions/cache@v2
        id: r-miniconda-cache
        with:
          path: ${{ env.RETICULATE_MINICONDA_PATH }}
          key: ${{ matrix.os }}--${{ steps.r-version.outputs.major-minor }}--tf-${{ matrix.tf }}
          restore-keys: ${{ runner.os }}--${{ steps.r-version.outputs.major-minor }}--tf-${{ matrix.tf }}

      - name: Install Miniconda
        if: steps.r-miniconda-cache.outputs.cache-hit != 'true'
        run: reticulate::install_miniconda()
        shell: Rscript {0}

      - name: Debug Output
        run: |
          env
          Rscript -e 'Sys.getenv()'
          Rscript -e 'reticulate::py_config()'

      - name: Install TensorFlow
        if: steps.r-miniconda-cache.outputs.cache-hit != 'true'
        shell: Rscript {0}
        run: |
          # reticulate::conda_create('r-reticulate')
          keras::install_keras(tensorflow = Sys.getenv("TF_VERSION"))
          print(reticulate::py_config())

      - name: Check
        shell: Rscript {0}
        run: |
          rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
